### ISSUE TITLE
Problem when running "poetry run experiment engine=code dataset.name=medqa_us dataset.subset=10"

### ISSUE THREAD

**Issue by funnyzhou** [vlievin/medical-reasoning#3]
Could not override 'engine'.
To append to your config use +engine=code
Key 'engine' is not in struct
    full_key: engine
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

After successfully installing poetry, I met a problem when running "poetry run experiment engine=code dataset.name=medqa_us dataset.subset=10". Could you please help me resolve it?

**Comment by vlievin** [comment]
Hi @funnyzhou,

To use the model configuration ´configs/model/engine/code.yaml´ use:

```bash
poetry run experiment model.engine=code
```

When using `hydra` the `+`indicates that you either want to extend the current config with a new variable (see [this page of the doc: "A simple command-line application"](https://hydra.cc/docs/tutorials/basic/your_first_app/simple_cli/))or override the config with global one (see [this page of the doc: "Configuring experiments"](https://hydra.cc/docs/patterns/configuring_experiments/)).

You can also use the `poe` to run the original experiments, see the `pyproject.toml` file.

Sorry for the late reply!
